### ISSUE TITLE
Unsuccessful every time I try to jailbreak.

### ISSUE THREAD

**Issue by liquidcaos** [opa334/Dopamine#209]
I've never had any issues with the prior versions but this one hasn't work not even once :( don't know if this could help ios 15.3 iPhone 11

[*] Launching kexploitd
[*] Hello from kernel exploit server!
[*] My UID is 0
[*] My GID is 0
[*] Launching oobPCI
[*] CP: 0x1b564
[*] GE: 0x15344
[*] SpawnDriver failed: failedToGetThreadState
E: The operation couldn’t be completed. (Fugu15KernelExploit.Fugu15LaunchError error 4.)

**Comment by Liam0205** [comment]
Yes, many people have reported this issue after upgrading to version 1.1. However, after examining the code, I couldn't identify why this problem would occur. Essentially, it calls the `thread_get_state` function in Obj-C, but the call is not successful (the return value is not `KERN_SUCCESS`). I have looked into several possibilities, but I couldn't find any potential causes in Dopamine for these issues:

1. Invalid thread identifier: If the thread identifier `tp` passed to the function is invalid or not a valid thread port, the function will return an error code instead of a successful return value.
2. Invalid state type: If the state type `type` passed to the function is invalid or unsupported, the function may return an error code.
3. Invalid state buffer: If the `thread_state_t` type state buffer passed to the function is invalid or insufficient to hold the thread state information, the function may return an error code.
4. Permission restrictions: If the calling thread does not have sufficient permissions to retrieve the specified thread's state information, the function may return an error code.

Perhaps there are other reasons that I'm not aware of that could be causing this problem?

**Comment by opa334** [comment]
Nothing has changed in the code related to this ever.
