### ISSUE TITLE
TrollStore and Dopamine can not open

### ISSUE THREAD

**Issue by miosx** [opa334/Dopamine#224]
TrollStore and Dopamine can not open
But other app can.

Updated to 1.1.1
It's like this after waking up

https://github.com/opa334/Dopamine/assets/131627176/6cd602ee-942b-4237-8a3d-7cb4b5e7c2f7

**Comment by Liam0205** [comment]
This is a known issue related to TrollStore.

> The CoreTrust bug used in TrollStore is only capable of installing "System" apps. This is because FrontBoard has an additional security check (it calls libmis) that runs every time before launching a user app. Unfortunately, it is not possible to install new "System" apps that persist through an icon cache reload. As a result, when iOS reloads the icon cache, all apps installed through TrollStore, including TrollStore itself, will revert back to the "User" state and will no longer launch.

To resolve this issue, you need to open GTA Car Tracker or use the Persistence Helper installed via TrollStore to re-register the relevant apps as System apps.

**Comment by miosx** [comment]
But Filza is also installed by TrollStore.
And Filza can run.
NewTerm is installed by Sileo.

**Comment by Liam0205** [comment]
> But Filza is also installed by TrollStore. And Filza can run. NewTerm is installed by Sileo.

To be honest, I'm somewhat skeptical. It seems unlikely from a technical standpoint. If you are convinced that this is a problem worth investigating, providing more information would be helpful. However, this discussion should be directed to the issue tracker of TrollStore rather than Dopamine.

Moreover, it is more important to address the problem you are currently facing. So, did refreshing the app's system state resolve the issue for you?

**Comment by miosx** [comment]
Yes, Reinstall TrollStore and Dopamine fix this issue.
But I'm telling the truth.
Close the issue now and I'll report more when it happens again.

**Comment by miosx** [comment]
Hope not to see it happens again :)
