### ISSUE TITLE
neko jb better

### ISSUE THREAD

**Issue by bradycodemaster** [opa334/Dopamine#324]

**Comment by bradleytechman** [comment]
nekoJB 
-supports 15.0 - 15.8 (not 15.8.1)
-errors are not descriptive at all (ex: ERR_MEOW)
-not open source (?)
-you can install Cydia
-15.8.1 is not supported.
+no need to uninstall palera1n


Dopamine
+open source
+supports iOS 15.0 - 16.6.1 
+errors very descriptive 
-cannot install cydia (probably for the best though)
-must uninstall palera1n

**Comment by Thyssenkrupp234** [comment]
nekoJB is still a great jailbreak, I personally run it on my 7 on 15.8. You cannot install cydia, no such port exists for iOS 15. The function doesn't work.

I agree that Dopamine is more stable, supports more versions, etc. Saying neko jb better is just false, although as a nekoJB16 tester myself, I think it's still a great tool and has lots of potential.

15.8.1 does technically work, but due to the current public beta being released prior to 15.8.1, with nobody knowing whether KFD was patched in that version, the app doesn't work. I assume once neko16 is finished and a public beta is out, 15.8.1 will be supported.

**Comment by xianquu** [comment]
I prefer palera1n.

I don’t want to sign ipa file.🌝

**Comment by libr2** [comment]
> I prefer palera1n.
> 
> 
> 
> I don’t want to sign ipa file.🌝

um have u heard of **trollstore**..
