### ISSUE TITLE
Problems with opening

### ISSUE THREAD

**Issue by Vladykin17** [opa334/Dopamine#332]
I can't open Dopamine by tapping on the app logo, but when I tap it in the list of opened apps, Dopamine opens.

iPhone 13, iOS 16.2

https://github.com/opa334/Dopamine/assets/102939212/eec6b835-04fc-48e4-a800-03a6896c7297

**Comment by Vladykin17** [comment]
Also, after a reboot, all apps(Sileo, Aemulo) disappeared.

**Comment by Zhou-Shilin** [comment]
> Also, after a reboot, all apps(Sileo, Aemulo) disappeared.

You need to reinstall after reboot as Dopamine is a rootless jailbreak.

**Comment by jacoboi13** [comment]
Happened to my iPhone X iOS 15.0.1, it was 2.0.3 latest that time when I jailbroken my idevice, but when 2.0.4 was released, I updated the dopamine tru app, it succeeded but after reboot I can't open the dopamine and sileo (and tweaks) are gone.

What was I did is that I uninstalled dopamine using trollstore, downloaded the latest dopamine 2.0.4 tipa from the official website then I rebooted my phone.

Reinstalled the latest dopamine tru trollstore and I re-jailbreak and then after userspace reboot all the things worked good, dopamine can be opened and it's on jailbroken, sileo appeared and tweaks are enabled.

Few things to note that this is "semi-untethered" rootless jailbreak, so you will lose jailbreak every after reboot, so you need to rejailbreak again tru dopamine jb app. 

If you need more questions, ask google or message tru discord jb channels, things are faster there rather than issuing issue here and only few people will reply to you.

**Comment by Zhou-Shilin** [comment]
> I can't open Dopamine by tapping on the app logo, but when I tap it in the list of opened apps, Dopamine opens.
> 
> iPhone 13, iOS 16.2
> 
>  IMG_7353.mov

switch dopamine to system registration 
[Updating dopamine via the app causes it to change to a user install type in trollstore #322](https://github.com/opa334/Dopamine/issues/322)

**Comment by opa334** [comment]
TrollStore Persistence Helper -> Refresh App Registrations
