### ISSUE TITLE
Plans for randomizing the /var/jb path

### ISSUE THREAD

**Issue by H5GG** [opa334/Dopamine#42]

**Comment by wwpp3399** [comment]
good

**Comment by segg21** [comment]
^ This. Proof apps is starting to detect `/var/jb` symlink, even when not in jailbroken state.
The only fix for this is deleting the symlink every time using Filza :/

Due to the nature of tweaks depending on this symlink to be permanent, I don't think there's a way to have `var/jb` randomized for each device. Would've been a good thought before Dopamine went this far in rootless development. 

For those who run into apps detecting jailbreak, the only resolution is deleting `var/jb`. There's no need to factory reset your entire device. This also will not delete your jb environment. `/var/jb` symlink would be restored next time you jailbreak.

Thought I would share since it took me a while to figure out what an app was detecting to consider my device being jailbroken.
