### ISSUE TITLE
Jailbreak Apps Disappear After a While

### ISSUE THREAD

**Issue by Sparktion** [opa334/Dopamine#484]
As title states. When jailbroken, tweaks will remain, but randomly, after a while (could be an hour or a day) my jailbreak apps disappear. I have the Sileo and iCleaner apps installed.

iOS: 16.2
Device: iPhone 14
Dopamine Ver: Latest (2.0.9)

Solution?

Most of the time, a respring brings the apps back. Sometimes, however, I need to userspace reboot and then respring.

EDIT:
Additionally, right after I jailbreak, my apps do not appear until I click "Restart SpringBoard"

**Comment by Hanze-Li** [comment]
Same issue.
iPhone 13 Pro
iOS 15.0.2
Dopamine 2.0.9

**Comment by xuemio73** [comment]
The same thing occurred to me. This is the second time.
The reason why all tweak apps disappeared was a problem with newly installed apps on the trollstore, and after disabling all tweak apps on iclenaer, the tweak apps disappeared.
After disabling all tweak apps on iclenaer, the tweak apps disappeared. The tweak apps disappeared and "Rebuild Icon Cache", "Userspace" and "tweak inject" were not working. I tried turning them on and off several times, but they did not come back. I also noticed that "Respring" does not work. (on dopamine app, on powerselctor's CC)
UPTIME is 53days.

I think the only solution is to reboot.
And I will update dopamine, but I see that v2 has the same problem...

**Comment by opa334** [comment]
There is absolutely nothing in the jailbreak that could cause this and additionally, nothing has changed in this regard since 1.x.

Of course when the system reloads the icon cache, jailbreak apps will disappear but it has always been this way on rootless jailbreaks and there is no easy way to fix this.

**Comment by xuemio73** [comment]
Okay, I have another dopamine jailbreak device that I rarely use and just charge, and the UPTIME was over 100 days.

So the problem with the disappearance of tweak apps is most likely caused by some manipulation by the jailbreak user.

I then re-breaked with dopamine 2.0.9 and the problem was not solved, the tweak apps did not show up.
I will now backup my tweak settings, delete dopamine and re-jailbreak.

**Comment by Sparktion** [comment]
I have found a tweak called "Jailbreak Icon Refresh" by zhaonan. I have only found it on Cypwn's repo. It's description is "Tweak to resolve Dopamine's inability to show Sileo or other applications after jailbreaking."

It seems to work great for me. Maybe this should be implemented into Dopamine? 

Found here: https://repo.cypwn.xyz/package/2030

**Comment by opa334** [comment]
> I have found a tweak called "Jailbreak Icon Refresh" by zhaonan. I have only found it on Cypwn's repo. It's description is "Tweak to resolve Dopamine's inability to show Sileo or other applications after jailbreaking."
> 
> It seems to work great for me. Maybe this should be implemented into Dopamine?
> 
> Found here: https://repo.cypwn.xyz/package/2030

I looked at this and it does the exact same thing as Dopamine itself. I fail to see how there would be any improvement by installing this package. Also just like Dopamine itself this only runs once on userspace reboots, there is no way this could fix "jailbreak apps disappearing after a while" (although I doubt this is even an actual issue to begin with)...

**Comment by Sparktion** [comment]
I'll try to look into the tweak that may be causing it, if it isn't dopamine itself. Thank you for your help.

Edit:
As Opa said, I have noticed that the tweak actually doesn't fix the issue.

**Comment by invalidunit** [comment]
> I looked at this and it does the exact same thing as Dopamine itself. I fail to see how there would be any improvement by installing this package. Also just like Dopamine itself this only runs once on userspace reboots, there is no way this could fix "jailbreak apps disappearing after a while" (although I doubt this is even an actual issue to begin with)...

Although it's unrelated to this particular issue, I created this package solely because my SE1 would not display any jailbreak icons (such as Sileo) after a jailbreak reboot—not even after waiting for 5 minutes. Moreover, I think that dopamine's default use of 'uicache -a' is too slow, and using 'uicache -p' can significantly speed things up, a fact that has been verified on my friend's iP7P as well.

**Comment by opa334** [comment]
> > I looked at this and it does the exact same thing as Dopamine itself. I fail to see how there would be any improvement by installing this package. Also just like Dopamine itself this only runs once on userspace reboots, there is no way this could fix "jailbreak apps disappearing after a while" (although I doubt this is even an actual issue to begin with)...
> 
> Although it's unrelated to this particular issue, I created this package solely because my SE1 would not display any jailbreak icons (such as Sileo) after a jailbreak reboot—not even after waiting for 5 minutes. Moreover, I think that dopamine's default use of 'uicache -a' is too slow, and using 'uicache -p' can significantly speed things up, a fact that has been verified on my friend's iP7P as well.

You're just not waiting for long enough then. `uicache -a` should do the exact same thing as running `uicache -p` on all applications manually. Usually it is pretty quick but in some isolated cases it can take up to two minutes for jailbreak apps to appear, the issue here is a lock-up in `lsd` and nothing related to uicache.

**Comment by eglacias** [comment]
The Dopamine jailbreak has the refresh jailbreak apps button. It also has reboot user space and respring. That’s gonna bring these things back, none of this is an issue with this jailbreak it seems.

Some of the wording in this issue is failing to logically present, typo/edit/concept errors… muddy.

Also, jailbreak tweaks, not apps, never disappear. It seems as if There’s No actual issues being discussed here which are related to this jailbreak?

**Comment by Sparktion** [comment]
> The Dopamine jailbreak has the refresh jailbreak apps button. It also has reboot user space and respring. That’s gonna bring these things back, none of this is an issue with this jailbreak it seems.
> 
> 
> 
> Some of the wording in this issue is failing to logically present, typo/edit/concept errors… muddy.
> 
> 
> 
> Also, jailbreak tweaks, not apps, never disappear. It seems as if There’s No actual issues being discussed here which are related to this jailbreak?

I think it does relate to the jailbreak(maybe not Dopamine's code itself) because Sileo and, for example, iCleaner Pro are only available through a dopamine environment. As for the buttons that "fix" the issue, the underlining issue still hasn't been solved: Jailbreak apps disappear after a while. Additionally, I do not think the wording of the issue is muddy, and if it is, please let me know of anything I could clarify and I'll be glad to!

**Comment by opa334** [comment]
The only actual issue that exists is that jailbreak apps disappear when the icon cache is reloaded, as the system does not honor /var/jb/Applications, let's track this in https://github.com/opa334/Dopamine/issues/496
